apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifest-signed
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "https://raw.githubusercontent.com/szemmour-rh/acs-cosgin-integration/main/app/deployment-signed.yaml"
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc create -f $(inputs.params.manifest_dir) -n demo
          echo -----------------------------------
