apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-api
  name: vote-api-signed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-api
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      containers:
        - image: quay.io/szemmour/pipelines-vote-api:signed
          imagePullPolicy: Always
          name: vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
